### ISSUE TITLE
Implementing the swapping in Local Search

### ISSUE THREAD

**Issue by np-harder** [embarg0/WeightedSetPackingLocal#1]
I haven't had time to implement this yet, but this was my rough idea in pseudocode for implementing the "swapping" part of the search:

Subset swapOut //already implemented
int previousTotalWeight  /*already implemented. Total weight of swapOut subset (NOT entire sol)....maybe change that name to previousPartialWeight or whatever */

//find a subset to swap in
1. choose a random recipie not in solution
2. a. check if not interesecting with solution
2. b. if interesecting, goto 1 (perhaps implement a new array to keep track of which recipies have been tried so far?).
2. c. else, add its weight to futurePartialWeight
3. Check if futurePartialWeight > previousTotalWeight. If so, this is your swapOut solution. If not, goto 1 again to add more recipes. 
4. If you run out of recipes to add and still not high enough weight... we can either terminate OR start all over again with new starting recipe for swapping out??? And do that y number of times, y=constant .????

We must decide on #4. I'm not sure what's best. 

Then:

//update currentRecipies and currentSol as needed.
// if you DO NOT actually find a better swapping subset, add the swapOut recipies back into solution. No need to change currentRecipies because that only gets changed when the swap is confirmed.

// else, update currentRecipies (a boolean array) to show that the swapped out subsets are not in solution anymore. And add the swapIn subsets to sol and update currentRecipies for swapIn, too

**Comment by treefridge** [comment]
Hmm one issue I see is that in finding a subset to swap in, that first subset/recipe that you can try to swap in must have a weight greater than the sum total of the subsets removed.. whereas there might have been 2 subsets whose combined weight was larger than the weight of the subsets removed

**Comment by treefridge** [comment]
https://www.dropbox.com/s/mas82hknc9wca1x/AlgoPseudocode.pdf?dl=0
my attempt at pseudocoding it, particularly inspired by the bottom of page 226 (it says page 26 in the doc, oops)

**Comment by treefridge** [comment]
Same thing, different words: 

![img_20150418_160705](https://cloud.githubusercontent.com/assets/6445091/7217084/6f7706a2-e5e5-11e4-90ef-44425c246900.jpg)

**Comment by np-harder** [comment]
Oh totally, I did didn't write that pseudo code very clearly.

If a subset G does not have high enough weight, then go to step 1 and add a
subset to G. You don't start all over, you stack the weights

**Comment by treefridge** [comment]
Ah, that makes sense : ) I think they both constitute as local search; now
I'm working on the second implementation from the above comments since the
paper more or less mentions what their version of local search was (bottom
of page 226).. (with my own assumptions added..)
