### ISSUE TITLE
Let's compute the neighbor matrix on the fly

### ISSUE THREAD

**Issue by treefridge** [embarg0/WeightedSetPackingLocal#3]
Currently:
local search expects a neighborMatrix to have been pre-computed for the current data, and simply checks for recipe collisions using this.

Aiming for:
The neighbor matrix to be filled in on the fly, and a value placeholder would indicate whether the collision has not yet been determined (in which case we would need to compare ingredient lists and update the neighbor matrix with the collision/no collision identifier for those recipes)

**Comment by np-harder** [comment]
I have implemented a solution. 

Currently:
- neighborMatrix is initialized to all 2s, ie "adjacency not yet computed".
- When the program comes across a neighborMatrix value of 2, the actual adjacency is computed with checkForDisjoint(Recipe recipe1, Recipe recipe2). This method updates neighborMatrix.
